# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-01-31 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('star', models.CharField(max_length=200)),
                ('num', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
